### ISSUE TITLE
Array index out-of-bounds error

### ISSUE THREAD

**Issue by sunstep** [drixevel-dev/sm-store#3]
I am getting the following error printed in my server console:

`L 12/29/2022 - 13:55:16: [SM] Exception reported: Array index out-of-bounds (index -1, limit 32)
L 12/29/2022 - 13:55:16: [SM] Blaming: default\store\core\store-backend.smx
L 12/29/2022 - 13:55:16: [SM] Call stack trace:
L 12/29/2022 - 13:55:16: [SM]   [1] Line 1863, C:\Users\Administrator\Desktop\everything\portables\tfserver\tf2\tf\addons\sourcemod\scripting\store-backend.sp::Native_GetLoadoutGame
L 12/29/2022 - 13:55:16: [SM]   [3] Store_GetLoadoutGame
L 12/29/2022 - 13:55:16: [SM]   [4] Line 257, C:\Users\Administrator\Desktop\everything\portables\tfserver\tf2\tf\addons\sourcemod\scripting\store-loadout.sp::IsLoadoutAvailableFor
L 12/29/2022 - 13:55:16: [SM]   [5] Line 167, C:\Users\Administrator\Desktop\everything\portables\tfserver\tf2\tf\addons\sourcemod\scripting\store-loadout.sp::Event_PlayerSpawn
`

It happens when the round starts in arena mode. Could you please look into this?

**Comment by drixevel-dev** [comment]
This should be fixed in the latest build.
